#!/bin/sh

# Script for using VIM as a TUI for devdocs

vimversion=`vim -e -T dumb --cmd 'exe "set t_cm=\<C-M>"|echo v:version|quit' | tr -d '\015' `
vimversion="${vimversion//[$'\t\r\n ']}"
if [ "$vimversion" -lt 901 ]; then
    echo 'Requires at least Vim 9.1'
    exit 1
fi

vim --cmd 'let no_plugin_maps = 1' --cmd 'let g:loaded_devdocs_tui = v:true' \
    -c 'runtime! plugin/setup.vim' \
    -c 'setl listchars=trail:\ ,tab:\ \ |setl fillchars=eob:\ ' \
    -c 'set statusline=%<\%{\"\ <esc>\ dismiss\ \|\ ^I\ install\ \|\ ^U\ uninstall\ \|\ ^F\ find\ \|\ /?\ search\ \|\ q\ quit\"}%=%-14.(%l,%c%V%)\ %P' \
    -c 'set shortmess=I ls=2|setl buftype=nofile noswapfile fdc=0 nofen nonu nornu bufhidden=hide nobuflisted noma' \
    -c 'nnoremap <silent> q :qa!<CR>|nnoremap <buffer> <silent> <c-f> <cmd>DevdocsFind<cr>|nnoremap <buffer> <silent> <c-i> <cmd>DevdocsInstall<cr>|nnoremap <buffer> <silent> <c-u> <cmd>DevdocsUninstall<cr>' \
    -c 'hi clear statusline|hi clear statuslinenc|hi default link DevdocMenuMatch String|hi default DevdocMenuCursor term=reverse cterm=reverse gui=reverse' \
    -c 'if g:DevdocsOptionsGet().data_dir->expand()->fnameescape()->isdirectory() | exe "DevdocsFind" | else | exe "DevdocsInstall" | endif'
